---
server:
  port: 8080
  contextPath: /wePro
---
spring:
  profiles: local, default, prod
datasource:
  weProapp:
    url: jdbc:mysql://localhost:3306/wePro
    username: root
    password: 
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect

